disabled_rules:
  - trailing_whitespace
  - opening_brace
  - identifier_name
  - file_length
opt_in_rules:
  - block_based_kvo
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - convenience_type
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - operator_usage_whitespace
  - todo
  - vertical_whitespace_closing_braces
  - strict_fileprivate
  - multiline_function_chains
  - multiline_parameters
  - multiline_parameters_brackets
line_length: 120
type_body_length:
  warning: 300
  error: 400
excluded:
  - Pods
